# Generated by Django 6.0.3 on 2026-03-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.FloatField()),
                ('soil_temperature', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('leaf_wetness', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
