# Generated by Django 6.0.3 on 2026-03-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_sensordata_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='plant_name',
            field=models.CharField(default='Unknown Crop', max_length=100),
        ),
    ]
